In [24]:
import numpy as np

In [40]:
arr = np.array([35.0, 75.0, 95.0])

In [41]:
arr

array([35., 75., 95.])

In [42]:
arr.dtype

dtype('float64')

In [43]:
arr = np.array([35.0, 75.0, 95.0], dtype = 'int64')

In [44]:
arr.dtype

dtype('int64')

In [28]:
# arr_integer = arr.astype(integer)

In [29]:
int_arr = arr.astype(int)

In [36]:
arr.dtype

dtype('float64')

In [31]:
arr

array([35., 75., 95.])

In [32]:
import numpy as np
arr = np.array([35.0, 75.0, 95.0])

# Convert float array to integer array
int_arr = arr.astype(int)

print(int_arr)            # Output: [35 75 95]
print(int_arr.dtype)      # Output: int64 or int32 depending on your system


[35 75 95]
int64


In [33]:
arr

array([35., 75., 95.])

In [45]:
import numpy as np       # this code was from prerplexcity

arr = np.array([35.0, 75.0, 95.0])
arr = arr.astype('int64')    # Explicitly convert to int64

print(arr)                   # Output: [35 75 95]
print(arr.dtype)             # Output: dtype('int64')


[35 75 95]
int64


In [38]:
arr

array([35, 75, 95])

In [39]:
arr.dtype

dtype('int64')

In [71]:
arr = np.array([35.0, 75.0, 95.0, 66, 77, 88, 99], dtype = 'int64')    # this code is from COH

In [72]:
arr

array([35, 75, 95, 66, 77, 88, 99])

In [54]:
import numpy as np         # This code was generated by Perplexcity

arr = np.array([35.0, 75.0, 95.0, 66, 77, 88, 99])

even_mask = arr % 2 == 0       # Boolean mask: True where element is even
even_numbers = arr[even_mask]  # Fancy indexing to get even numbers

print(even_numbers)            # Output: [66. 88.]


[66. 88.]


In [77]:
arr = np.array([35.0, 75.0, 95.0, 66, 77, 88, 99])

In [75]:
evarr = arr % 2 == 0
even_numbers = arr[evarr]
print(even_numbers)

[66 88]


In [76]:
evarr

array([False, False, False,  True, False,  True, False])

In [113]:
arr = np.array([35.0, 75.0, 95.0, 66, 77, 88, 99, 100], dtype = 'int64')

In [114]:
arr.dtype

dtype('int64')

In [115]:
arr

array([ 35,  75,  95,  66,  77,  88,  99, 100])

In [91]:
arr = np.array([[35.0, 75.0], [95.0, 66], [77, 88], [99, 100]])

In [118]:
arr

array([ 35,  75,  95,  66,  77,  88,  99, 100])

In [99]:
arr.reshape(2, 4)

array([[ 35.,  75.,  95.,  66.],
       [ 77.,  88.,  99., 100.]])

In [116]:
arr[arr > 75]

array([ 95,  77,  88,  99, 100])

In [117]:
arr

array([ 35,  75,  95,  66,  77,  88,  99, 100])

In [119]:
# Practice the below projects