In [2]:
# Python zip explained
l1 = [1, 2, 4]
l2 = [6, 7, 8]
list(zip(l1,l2))

[(1, 6), (2, 7), (4, 8)]

In [5]:
# using python list

import numpy as np
import time

size = 1_000_000

l1 = list(range(size))
l2 = list(range(size))

start = time.time()
add = [x+y for x,y in zip (l1, l2)]
end = time.time()
print(add[0:11])

print(end - start)


[0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20]
0.26148533821105957


In [7]:
# using numpy Arrays

import numpy as np
import time

size = 1_000_000

l1 = np.array(list(range(size)))
l2 = np.array(list(range(size)))

start = time.time()
add = l1 + l2
end = time.time()
print(add[0:11])

print(end - start)


[ 0  2  4  6  8 10 12 14 16 18 20]
0.006100177764892578


In [10]:
np.array([1, 2, 3, 4, 5, "Harry"])

array(['1', '2', '3', '4', '5', 'Harry'], dtype='<U21')

In [11]:
np.array([1, 2, 3, 4, 5])

array([1, 2, 3, 4, 5])

In [15]:
np.array([[1, 2, 3], [4, 5, 6]]) #LHS = RHS If not it will show error

array([[1, 2, 3],
       [4, 5, 6]])

In [16]:
arr = np.array([[1, 2, 3], [4, 5, 6]]) 

In [17]:
type(arr)

numpy.ndarray

In [19]:
arr.shape # Two rows , Three Coloms

(2, 3)

In [22]:
import sys
list_data = list(range(1000))
numpy_data = np.array(list_data)
print("Python list size:", sys.getsizeof(list_data) * len(list_data), "bytes")
print("numPy array size:", numpy_data.nbytes, "bytes")

Python list size: 8056000 bytes
numPy array size: 8000 bytes


In [28]:
list1 = [1, 2, 3, 4, 5]
list_squares = [x**2 for x in list1]
print("python list squares", list_squares)
print("python list size:", sys.getsizeof(list_data) * len(list_data), "bytes")

python list squares [1, 4, 9, 16, 25]
python list size: 8056000 bytes


In [30]:
import sys
import numpy as np

# Sample data
list1 = list(range(1000))
arr1 = np.array(list1)

# Calculating squares
list_squares = [x**2 for x in list1]
numpy_squares = arr1 ** 2

# Correct memory size calculation
print("python list size:", sys.getsizeof(list_squares), "bytes")
print("Numpy array size:", numpy_squares.nbytes, "bytes")


python list size: 8856 bytes
Numpy array size: 8000 bytes
