In [13]:
import numpy as np
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])


arr_float = arr.astype(float)
print(arr_float)
print(arr_float.dtype)  # Output: float64


[[ 1.  2.  3.]
 [ 4.  5.  6.]
 [ 7.  8.  9.]
 [10. 11. 12.]]
float64


In [14]:
arr[0]

array([1, 2, 3])

In [15]:
flat = arr.flatten()

In [16]:
flat

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [17]:
flat[0]

np.int64(1)

In [18]:
flat[3: 6]

array([4, 5, 6])

In [19]:
flat[:5]     # same as [0:5]

array([1, 2, 3, 4, 5])

In [20]:
flat[3:]    # same as [3:12]

array([ 4,  5,  6,  7,  8,  9, 10, 11, 12])

In [21]:
flat[3:12]

array([ 4,  5,  6,  7,  8,  9, 10, 11, 12])

In [22]:
flat

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [23]:
b = flat[3:7]

In [24]:
b

array([4, 5, 6, 7])

In [25]:
b[0] = 44444

In [26]:
b

array([44444,     5,     6,     7])

In [36]:
flat     # (b) dose change the view of flat/view/original array    /   these are mutable

array([    1,     2,     3, 44444,     5,     6,     7,     8,     9,
          10,    11,    12])

In [37]:
b = flat[3:7].copy()       # THIS IS NOT A SCLICE, BECAUSE WE ARE USING COPY METHOD.

In [30]:
b

array([44444,     5,     6,     7])

In [31]:
b[0] = 66666

In [32]:
b

array([66666,     5,     6,     7])

In [34]:
flat     # Because we used copy method it wont cahnge the view/flat/ original array

array([    1,     2,     3, 44444,     5,     6,     7,     8,     9,
          10,    11,    12])

In [39]:
arr = np.array([1, 23, 45, 78, 96, 54 , 35])

In [43]:
arr[[1, 4, 6]]          # Fancy Indexing   ,    seleecting Multiple Elements

array([23, 96, 35])

In [46]:
arr[arr>23]            # Boolean Masking    ,    Filter data

array([45, 78, 96, 54, 35])

In [47]:
arr[arr>35]

array([45, 78, 96, 54])