In [36]:
# Axis in 2D array            - rows and coloums

import numpy as np    

arr = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])


In [12]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [13]:
arr[0]

array([1, 2, 3])

In [14]:
arr[1]

array([4, 5, 6])

In [15]:
arr[2]

array([7, 8, 9])

In [16]:
np.sum(arr, axis=0)

array([12, 15, 18])

In [17]:
np.sum(arr, axis=1)

array([ 6, 15, 24])

In [31]:
# Indexing in Multidimension array    

In [19]:
arr[0][1]

np.int64(2)

In [20]:
arr[0, 1]

np.int64(2)

In [21]:
arr[0:2, 1:3]

array([[2, 3],
       [5, 6]])

In [35]:
# Indexing in 3D         - Depth, rows and coloums

In [27]:
arr3D = np.array([[[1, 2, 3], [4, 5, 6]],
                 [[7, 8, 9], [10, 11, 12]]])

In [32]:
print(arr3D.shape)

(2, 2, 3)


In [33]:
print(arr3D[0, 1, 2])

6


In [30]:
print(arr3D[:, 0, :])

[[1 2 3]
 [7 8 9]]


In [38]:
print(arr3D[0, 0, :])

[1 2 3]


In [40]:
print(arr3D[:, 0, 0])

[1 7]


In [41]:
# Practical Example: Selecting data along 

In [45]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [44]:
# Get all rows of the first coloum
first_col = arr[:, 0]
print(first_col)

[1 4 7]


In [47]:
arr3D

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [46]:
# Get the first row from each "sheet" in a 3D array
first_rows = arr3D[:, 0, :]
print(first_rows)

[[1 2 3]
 [7 8 9]]


In [48]:
#

In [49]:
arr3D[:, 0, 0] = 0

In [50]:
arr3D

array([[[ 0,  2,  3],
        [ 4,  5,  6]],

       [[ 0,  8,  9],
        [10, 11, 12]]])

In [52]:
arr3D[:, 0, :] = 0

In [53]:
arr3D

array([[[ 0,  0,  0],
        [ 4,  5,  6]],

       [[ 0,  0,  0],
        [10, 11, 12]]])