In [1]:
# vecterization formula

import numpy as np

In [3]:
arr = np.array([1, 2, 3, 4, 5])
result = arr ** 2   # Vecterization Operation
print(result)

[ 1  4  9 16 25]


In [4]:
result + 10

array([11, 14, 19, 26, 35])

In [5]:
# Broadcasting with arrays of different shapes

In [8]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([10, 20, 30])

result = arr1 + arr2
result

array([11, 22, 33])

In [11]:
arr1 = np.array([[1, 2, 3], [4, 5, 6]])   # 2D
arr2 = np.array([1, 2, 3])                # 1D

result = arr1 + arr2                      # 2D + 1D
result

array([[2, 4, 6],
       [5, 7, 9]])

In [14]:
# Simulating a dataset (5 sample, 3 feature)

data = np.array([[10, 20, 30],
                [15, 25, 35],
                [20, 30, 40],
                [25, 35, 45],
                [30, 40 ,50]])

# Calcuating the mean and standard divisation for each feature.
mean = data.mean(axis = 0)
std = data.std(axis = 0)

# Normalisation the data using Broadcasting
normalized_data = (data - mean) / std

print(normalized_data)

[[-1.41421356 -1.41421356 -1.41421356]
 [-0.70710678 -0.70710678 -0.70710678]
 [ 0.          0.          0.        ]
 [ 0.70710678  0.70710678  0.70710678]
 [ 1.41421356  1.41421356  1.41421356]]
