In [2]:
import numpy as np

In [3]:
arr = np.array([3, 5, 2, 33])

In [4]:
np.mean(arr)

np.float64(10.75)

In [6]:
np.min(arr)

np.int64(2)

In [7]:
np.max(arr)

np.int64(33)

In [10]:
np.std(arr)    #Standard diviation

np.float64(12.891373084353738)

In [11]:
np.var(arr)    #Variance

np.float64(166.1875)

In [13]:
np.sum(arr)    # sum of all 

np.int64(43)

In [16]:
np.prod(arr)     #product of all elements / multiply all 

np.int64(990)

In [17]:
np.median(arr)    #median

np.float64(4.0)

In [18]:
np.percentile(arr, 50)   #

np.float64(4.0)

In [19]:
np.argmin(arr)     #retuen index of minimun

np.int64(2)

In [20]:
np.argmax(arr)    # return index of max

np.int64(3)

In [21]:
np.corrcoef(arr)   # corelation - coeffection

np.float64(1.0)

In [22]:
arr = np.array([3, 5, 2, 33, 2, 1, 10, 1])

In [24]:
np.unique(arr)    #  ***Highly used***   Finds unique elements

array([ 1,  2,  3,  5, 10, 33])

In [26]:
np.cumsum(arr)    #Cumalative sum

array([ 3,  8, 10, 43, 45, 46, 56, 57])

In [28]:
np.diff(arr)    # n'th  difference

array([  2,  -3,  31, -31,  -1,   9,  -9])

In [39]:
np.linspace(0, 10, 5)    #evenly space numbers

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [38]:
np.log(arr)    # natural algorithm

array([1.09861229, 1.60943791, 0.69314718, 3.49650756, 0.69314718,
       0.        , 2.30258509, 0.        ])

In [40]:
np.exp(arr)   # expodential

array([2.00855369e+01, 1.48413159e+02, 7.38905610e+00, 2.14643580e+14,
       7.38905610e+00, 2.71828183e+00, 2.20264658e+04, 2.71828183e+00])